//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wstcp.DEVINO {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandStatus", Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public enum CommandStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK_Operation_Completed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Not_Enough_Credits = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Message_Rejected = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Invalid_Source_Address = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Invalid_Destination_Address = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_SMS_User_Disabled = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Invalid_MessageID = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Invalid_Header = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Invalid_Login = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Invalid_Password = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Unauthorised_IP_Address = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Invalid_Activation_Code = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_SMS_User_Not_Activated = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Message_Queue_Full = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Gateway_Offline = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Gateway_Busy = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Database_Offline = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_No_Messages_Selected = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Outbox_Empty = 18,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageState", Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public enum MessageState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enqueued = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivered_To_Gateway = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivered_To_Recipient = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Invalid_Destination_Address = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Invalid_Source_Address = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Incompatible_Destination = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Rejected = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Expired = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://gw1.devinosms.com/WebService.asmx", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gw1.devinosms.com/WebService.asmx", ConfigurationName="DEVINO.DEVINOSoap")]
    public interface DEVINOSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw1.devinosms.com/WebService.asmx/GetCreditBalance", ReplyAction="*")]
        wstcp.DEVINO.GetCreditBalanceResponse GetCreditBalance(wstcp.DEVINO.GetCreditBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw1.devinosms.com/WebService.asmx/GetCreditBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<wstcp.DEVINO.GetCreditBalanceResponse> GetCreditBalanceAsync(wstcp.DEVINO.GetCreditBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw1.devinosms.com/WebService.asmx/GetMessageState", ReplyAction="*")]
        wstcp.DEVINO.GetMessageStateResponse GetMessageState(wstcp.DEVINO.GetMessageStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw1.devinosms.com/WebService.asmx/GetMessageState", ReplyAction="*")]
        System.Threading.Tasks.Task<wstcp.DEVINO.GetMessageStateResponse> GetMessageStateAsync(wstcp.DEVINO.GetMessageStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw1.devinosms.com/WebService.asmx/GetMessageState2", ReplyAction="*")]
        wstcp.DEVINO.GetMessageState2Response GetMessageState2(wstcp.DEVINO.GetMessageState2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw1.devinosms.com/WebService.asmx/GetMessageState2", ReplyAction="*")]
        System.Threading.Tasks.Task<wstcp.DEVINO.GetMessageState2Response> GetMessageState2Async(wstcp.DEVINO.GetMessageState2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw1.devinosms.com/WebService.asmx/SendTextMessage", ReplyAction="*")]
        wstcp.DEVINO.SendTextMessageResponse SendTextMessage(wstcp.DEVINO.SendTextMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw1.devinosms.com/WebService.asmx/SendTextMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<wstcp.DEVINO.SendTextMessageResponse> SendTextMessageAsync(wstcp.DEVINO.SendTextMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw1.devinosms.com/WebService.asmx/SendWapPushSMS", ReplyAction="*")]
        wstcp.DEVINO.SendWapPushSMSResponse SendWapPushSMS(wstcp.DEVINO.SendWapPushSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gw1.devinosms.com/WebService.asmx/SendWapPushSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<wstcp.DEVINO.SendWapPushSMSResponse> SendWapPushSMSAsync(wstcp.DEVINO.SendWapPushSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditBalance", Namespace="http://gw1.devinosms.com/WebService.asmx", Order=0)]
        public wstcp.DEVINO.GetCreditBalanceRequestBody Body;
        
        public GetCreditBalanceRequest() {
        }
        
        public GetCreditBalanceRequest(wstcp.DEVINO.GetCreditBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public partial class GetCreditBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetCreditBalanceRequestBody() {
        }
        
        public GetCreditBalanceRequestBody(string smsUser, string password) {
            this.smsUser = smsUser;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditBalanceResponse", Namespace="http://gw1.devinosms.com/WebService.asmx", Order=0)]
        public wstcp.DEVINO.GetCreditBalanceResponseBody Body;
        
        public GetCreditBalanceResponse() {
        }
        
        public GetCreditBalanceResponse(wstcp.DEVINO.GetCreditBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public partial class GetCreditBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public wstcp.DEVINO.CommandStatus GetCreditBalanceResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal creditBalance;
        
        public GetCreditBalanceResponseBody() {
        }
        
        public GetCreditBalanceResponseBody(wstcp.DEVINO.CommandStatus GetCreditBalanceResult, decimal creditBalance) {
            this.GetCreditBalanceResult = GetCreditBalanceResult;
            this.creditBalance = creditBalance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageState", Namespace="http://gw1.devinosms.com/WebService.asmx", Order=0)]
        public wstcp.DEVINO.GetMessageStateRequestBody Body;
        
        public GetMessageStateRequest() {
        }
        
        public GetMessageStateRequest(wstcp.DEVINO.GetMessageStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public partial class GetMessageStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageId;
        
        public GetMessageStateRequestBody() {
        }
        
        public GetMessageStateRequestBody(string smsUser, string password, string messageId) {
            this.smsUser = smsUser;
            this.password = password;
            this.messageId = messageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStateResponse", Namespace="http://gw1.devinosms.com/WebService.asmx", Order=0)]
        public wstcp.DEVINO.GetMessageStateResponseBody Body;
        
        public GetMessageStateResponse() {
        }
        
        public GetMessageStateResponse(wstcp.DEVINO.GetMessageStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public partial class GetMessageStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public wstcp.DEVINO.CommandStatus GetMessageStateResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime reportedDateUtc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public wstcp.DEVINO.MessageState messageState;
        
        public GetMessageStateResponseBody() {
        }
        
        public GetMessageStateResponseBody(wstcp.DEVINO.CommandStatus GetMessageStateResult, System.DateTime reportedDateUtc, wstcp.DEVINO.MessageState messageState) {
            this.GetMessageStateResult = GetMessageStateResult;
            this.reportedDateUtc = reportedDateUtc;
            this.messageState = messageState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageState2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageState2", Namespace="http://gw1.devinosms.com/WebService.asmx", Order=0)]
        public wstcp.DEVINO.GetMessageState2RequestBody Body;
        
        public GetMessageState2Request() {
        }
        
        public GetMessageState2Request(wstcp.DEVINO.GetMessageState2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public partial class GetMessageState2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageId;
        
        public GetMessageState2RequestBody() {
        }
        
        public GetMessageState2RequestBody(string smsUser, string password, string messageId) {
            this.smsUser = smsUser;
            this.password = password;
            this.messageId = messageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageState2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageState2Response", Namespace="http://gw1.devinosms.com/WebService.asmx", Order=0)]
        public wstcp.DEVINO.GetMessageState2ResponseBody Body;
        
        public GetMessageState2Response() {
        }
        
        public GetMessageState2Response(wstcp.DEVINO.GetMessageState2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public partial class GetMessageState2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public wstcp.DEVINO.CommandStatus GetMessageState2Result;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime reportedDateUtc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public wstcp.DEVINO.MessageState messageState;
        
        public GetMessageState2ResponseBody() {
        }
        
        public GetMessageState2ResponseBody(wstcp.DEVINO.CommandStatus GetMessageState2Result, System.DateTime reportedDateUtc, wstcp.DEVINO.MessageState messageState) {
            this.GetMessageState2Result = GetMessageState2Result;
            this.reportedDateUtc = reportedDateUtc;
            this.messageState = messageState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTextMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTextMessage", Namespace="http://gw1.devinosms.com/WebService.asmx", Order=0)]
        public wstcp.DEVINO.SendTextMessageRequestBody Body;
        
        public SendTextMessageRequest() {
        }
        
        public SendTextMessageRequest(wstcp.DEVINO.SendTextMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public partial class SendTextMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destinationAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string messageData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sourceAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool deliveryReport;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool flashMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int validityPeriod;
        
        public SendTextMessageRequestBody() {
        }
        
        public SendTextMessageRequestBody(string smsUser, string password, string destinationAddress, string messageData, string sourceAddress, bool deliveryReport, bool flashMessage, int validityPeriod) {
            this.smsUser = smsUser;
            this.password = password;
            this.destinationAddress = destinationAddress;
            this.messageData = messageData;
            this.sourceAddress = sourceAddress;
            this.deliveryReport = deliveryReport;
            this.flashMessage = flashMessage;
            this.validityPeriod = validityPeriod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTextMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTextMessageResponse", Namespace="http://gw1.devinosms.com/WebService.asmx", Order=0)]
        public wstcp.DEVINO.SendTextMessageResponseBody Body;
        
        public SendTextMessageResponse() {
        }
        
        public SendTextMessageResponse(wstcp.DEVINO.SendTextMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public partial class SendTextMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public wstcp.DEVINO.CommandStatus SendTextMessageResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public wstcp.DEVINO.ArrayOfString messageId;
        
        public SendTextMessageResponseBody() {
        }
        
        public SendTextMessageResponseBody(wstcp.DEVINO.CommandStatus SendTextMessageResult, wstcp.DEVINO.ArrayOfString messageId) {
            this.SendTextMessageResult = SendTextMessageResult;
            this.messageId = messageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWapPushSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWapPushSMS", Namespace="http://gw1.devinosms.com/WebService.asmx", Order=0)]
        public wstcp.DEVINO.SendWapPushSMSRequestBody Body;
        
        public SendWapPushSMSRequest() {
        }
        
        public SendWapPushSMSRequest(wstcp.DEVINO.SendWapPushSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public partial class SendWapPushSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smsUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destinationAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WapUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DescriptionText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sourceAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool deliveryReport;
        
        public SendWapPushSMSRequestBody() {
        }
        
        public SendWapPushSMSRequestBody(string smsUser, string password, string destinationAddress, string WapUrl, string DescriptionText, string sourceAddress, bool deliveryReport) {
            this.smsUser = smsUser;
            this.password = password;
            this.destinationAddress = destinationAddress;
            this.WapUrl = WapUrl;
            this.DescriptionText = DescriptionText;
            this.sourceAddress = sourceAddress;
            this.deliveryReport = deliveryReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWapPushSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWapPushSMSResponse", Namespace="http://gw1.devinosms.com/WebService.asmx", Order=0)]
        public wstcp.DEVINO.SendWapPushSMSResponseBody Body;
        
        public SendWapPushSMSResponse() {
        }
        
        public SendWapPushSMSResponse(wstcp.DEVINO.SendWapPushSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gw1.devinosms.com/WebService.asmx")]
    public partial class SendWapPushSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public wstcp.DEVINO.CommandStatus SendWapPushSMSResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public wstcp.DEVINO.ArrayOfString messageId;
        
        public SendWapPushSMSResponseBody() {
        }
        
        public SendWapPushSMSResponseBody(wstcp.DEVINO.CommandStatus SendWapPushSMSResult, wstcp.DEVINO.ArrayOfString messageId) {
            this.SendWapPushSMSResult = SendWapPushSMSResult;
            this.messageId = messageId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DEVINOSoapChannel : wstcp.DEVINO.DEVINOSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DEVINOSoapClient : System.ServiceModel.ClientBase<wstcp.DEVINO.DEVINOSoap>, wstcp.DEVINO.DEVINOSoap {
        
        public DEVINOSoapClient() {
        }
        
        public DEVINOSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DEVINOSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DEVINOSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DEVINOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wstcp.DEVINO.GetCreditBalanceResponse wstcp.DEVINO.DEVINOSoap.GetCreditBalance(wstcp.DEVINO.GetCreditBalanceRequest request) {
            return base.Channel.GetCreditBalance(request);
        }
        
        public wstcp.DEVINO.CommandStatus GetCreditBalance(string smsUser, string password, out decimal creditBalance) {
            wstcp.DEVINO.GetCreditBalanceRequest inValue = new wstcp.DEVINO.GetCreditBalanceRequest();
            inValue.Body = new wstcp.DEVINO.GetCreditBalanceRequestBody();
            inValue.Body.smsUser = smsUser;
            inValue.Body.password = password;
            wstcp.DEVINO.GetCreditBalanceResponse retVal = ((wstcp.DEVINO.DEVINOSoap)(this)).GetCreditBalance(inValue);
            creditBalance = retVal.Body.creditBalance;
            return retVal.Body.GetCreditBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wstcp.DEVINO.GetCreditBalanceResponse> wstcp.DEVINO.DEVINOSoap.GetCreditBalanceAsync(wstcp.DEVINO.GetCreditBalanceRequest request) {
            return base.Channel.GetCreditBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<wstcp.DEVINO.GetCreditBalanceResponse> GetCreditBalanceAsync(string smsUser, string password) {
            wstcp.DEVINO.GetCreditBalanceRequest inValue = new wstcp.DEVINO.GetCreditBalanceRequest();
            inValue.Body = new wstcp.DEVINO.GetCreditBalanceRequestBody();
            inValue.Body.smsUser = smsUser;
            inValue.Body.password = password;
            return ((wstcp.DEVINO.DEVINOSoap)(this)).GetCreditBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wstcp.DEVINO.GetMessageStateResponse wstcp.DEVINO.DEVINOSoap.GetMessageState(wstcp.DEVINO.GetMessageStateRequest request) {
            return base.Channel.GetMessageState(request);
        }
        
        public wstcp.DEVINO.CommandStatus GetMessageState(string smsUser, string password, string messageId, out System.DateTime reportedDateUtc, out wstcp.DEVINO.MessageState messageState) {
            wstcp.DEVINO.GetMessageStateRequest inValue = new wstcp.DEVINO.GetMessageStateRequest();
            inValue.Body = new wstcp.DEVINO.GetMessageStateRequestBody();
            inValue.Body.smsUser = smsUser;
            inValue.Body.password = password;
            inValue.Body.messageId = messageId;
            wstcp.DEVINO.GetMessageStateResponse retVal = ((wstcp.DEVINO.DEVINOSoap)(this)).GetMessageState(inValue);
            reportedDateUtc = retVal.Body.reportedDateUtc;
            messageState = retVal.Body.messageState;
            return retVal.Body.GetMessageStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wstcp.DEVINO.GetMessageStateResponse> wstcp.DEVINO.DEVINOSoap.GetMessageStateAsync(wstcp.DEVINO.GetMessageStateRequest request) {
            return base.Channel.GetMessageStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<wstcp.DEVINO.GetMessageStateResponse> GetMessageStateAsync(string smsUser, string password, string messageId) {
            wstcp.DEVINO.GetMessageStateRequest inValue = new wstcp.DEVINO.GetMessageStateRequest();
            inValue.Body = new wstcp.DEVINO.GetMessageStateRequestBody();
            inValue.Body.smsUser = smsUser;
            inValue.Body.password = password;
            inValue.Body.messageId = messageId;
            return ((wstcp.DEVINO.DEVINOSoap)(this)).GetMessageStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wstcp.DEVINO.GetMessageState2Response wstcp.DEVINO.DEVINOSoap.GetMessageState2(wstcp.DEVINO.GetMessageState2Request request) {
            return base.Channel.GetMessageState2(request);
        }
        
        public wstcp.DEVINO.CommandStatus GetMessageState2(string smsUser, string password, string messageId, out System.DateTime reportedDateUtc, out wstcp.DEVINO.MessageState messageState) {
            wstcp.DEVINO.GetMessageState2Request inValue = new wstcp.DEVINO.GetMessageState2Request();
            inValue.Body = new wstcp.DEVINO.GetMessageState2RequestBody();
            inValue.Body.smsUser = smsUser;
            inValue.Body.password = password;
            inValue.Body.messageId = messageId;
            wstcp.DEVINO.GetMessageState2Response retVal = ((wstcp.DEVINO.DEVINOSoap)(this)).GetMessageState2(inValue);
            reportedDateUtc = retVal.Body.reportedDateUtc;
            messageState = retVal.Body.messageState;
            return retVal.Body.GetMessageState2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wstcp.DEVINO.GetMessageState2Response> wstcp.DEVINO.DEVINOSoap.GetMessageState2Async(wstcp.DEVINO.GetMessageState2Request request) {
            return base.Channel.GetMessageState2Async(request);
        }
        
        public System.Threading.Tasks.Task<wstcp.DEVINO.GetMessageState2Response> GetMessageState2Async(string smsUser, string password, string messageId) {
            wstcp.DEVINO.GetMessageState2Request inValue = new wstcp.DEVINO.GetMessageState2Request();
            inValue.Body = new wstcp.DEVINO.GetMessageState2RequestBody();
            inValue.Body.smsUser = smsUser;
            inValue.Body.password = password;
            inValue.Body.messageId = messageId;
            return ((wstcp.DEVINO.DEVINOSoap)(this)).GetMessageState2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wstcp.DEVINO.SendTextMessageResponse wstcp.DEVINO.DEVINOSoap.SendTextMessage(wstcp.DEVINO.SendTextMessageRequest request) {
            return base.Channel.SendTextMessage(request);
        }
        
        public wstcp.DEVINO.CommandStatus SendTextMessage(string smsUser, string password, string destinationAddress, string messageData, string sourceAddress, bool deliveryReport, bool flashMessage, int validityPeriod, out wstcp.DEVINO.ArrayOfString messageId) {
            wstcp.DEVINO.SendTextMessageRequest inValue = new wstcp.DEVINO.SendTextMessageRequest();
            inValue.Body = new wstcp.DEVINO.SendTextMessageRequestBody();
            inValue.Body.smsUser = smsUser;
            inValue.Body.password = password;
            inValue.Body.destinationAddress = destinationAddress;
            inValue.Body.messageData = messageData;
            inValue.Body.sourceAddress = sourceAddress;
            inValue.Body.deliveryReport = deliveryReport;
            inValue.Body.flashMessage = flashMessage;
            inValue.Body.validityPeriod = validityPeriod;
            wstcp.DEVINO.SendTextMessageResponse retVal = ((wstcp.DEVINO.DEVINOSoap)(this)).SendTextMessage(inValue);
            messageId = retVal.Body.messageId;
            return retVal.Body.SendTextMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wstcp.DEVINO.SendTextMessageResponse> wstcp.DEVINO.DEVINOSoap.SendTextMessageAsync(wstcp.DEVINO.SendTextMessageRequest request) {
            return base.Channel.SendTextMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<wstcp.DEVINO.SendTextMessageResponse> SendTextMessageAsync(string smsUser, string password, string destinationAddress, string messageData, string sourceAddress, bool deliveryReport, bool flashMessage, int validityPeriod) {
            wstcp.DEVINO.SendTextMessageRequest inValue = new wstcp.DEVINO.SendTextMessageRequest();
            inValue.Body = new wstcp.DEVINO.SendTextMessageRequestBody();
            inValue.Body.smsUser = smsUser;
            inValue.Body.password = password;
            inValue.Body.destinationAddress = destinationAddress;
            inValue.Body.messageData = messageData;
            inValue.Body.sourceAddress = sourceAddress;
            inValue.Body.deliveryReport = deliveryReport;
            inValue.Body.flashMessage = flashMessage;
            inValue.Body.validityPeriod = validityPeriod;
            return ((wstcp.DEVINO.DEVINOSoap)(this)).SendTextMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wstcp.DEVINO.SendWapPushSMSResponse wstcp.DEVINO.DEVINOSoap.SendWapPushSMS(wstcp.DEVINO.SendWapPushSMSRequest request) {
            return base.Channel.SendWapPushSMS(request);
        }
        
        public wstcp.DEVINO.CommandStatus SendWapPushSMS(string smsUser, string password, string destinationAddress, string WapUrl, string DescriptionText, string sourceAddress, bool deliveryReport, out wstcp.DEVINO.ArrayOfString messageId) {
            wstcp.DEVINO.SendWapPushSMSRequest inValue = new wstcp.DEVINO.SendWapPushSMSRequest();
            inValue.Body = new wstcp.DEVINO.SendWapPushSMSRequestBody();
            inValue.Body.smsUser = smsUser;
            inValue.Body.password = password;
            inValue.Body.destinationAddress = destinationAddress;
            inValue.Body.WapUrl = WapUrl;
            inValue.Body.DescriptionText = DescriptionText;
            inValue.Body.sourceAddress = sourceAddress;
            inValue.Body.deliveryReport = deliveryReport;
            wstcp.DEVINO.SendWapPushSMSResponse retVal = ((wstcp.DEVINO.DEVINOSoap)(this)).SendWapPushSMS(inValue);
            messageId = retVal.Body.messageId;
            return retVal.Body.SendWapPushSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wstcp.DEVINO.SendWapPushSMSResponse> wstcp.DEVINO.DEVINOSoap.SendWapPushSMSAsync(wstcp.DEVINO.SendWapPushSMSRequest request) {
            return base.Channel.SendWapPushSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wstcp.DEVINO.SendWapPushSMSResponse> SendWapPushSMSAsync(string smsUser, string password, string destinationAddress, string WapUrl, string DescriptionText, string sourceAddress, bool deliveryReport) {
            wstcp.DEVINO.SendWapPushSMSRequest inValue = new wstcp.DEVINO.SendWapPushSMSRequest();
            inValue.Body = new wstcp.DEVINO.SendWapPushSMSRequestBody();
            inValue.Body.smsUser = smsUser;
            inValue.Body.password = password;
            inValue.Body.destinationAddress = destinationAddress;
            inValue.Body.WapUrl = WapUrl;
            inValue.Body.DescriptionText = DescriptionText;
            inValue.Body.sourceAddress = sourceAddress;
            inValue.Body.deliveryReport = deliveryReport;
            return ((wstcp.DEVINO.DEVINOSoap)(this)).SendWapPushSMSAsync(inValue);
        }
    }
}
